# Generated by Django 4.2.7 on 2023-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_value', models.FloatField()),
                ('quantity_hours', models.IntegerField()),
                ('commission_percentage', models.FloatField()),
                ('bedroom_hours', models.IntegerField()),
                ('bedroom_value', models.FloatField()),
                ('living_room_hours', models.IntegerField()),
                ('living_room_value', models.FloatField()),
                ('bathroom_hours', models.IntegerField()),
                ('bathroom_value', models.FloatField()),
                ('kitchen_hours', models.IntegerField()),
                ('kitchen_value', models.FloatField()),
                ('backyard_hours', models.IntegerField()),
                ('backyard_value', models.FloatField()),
                ('other_hours', models.IntegerField()),
                ('other_value', models.FloatField()),
                ('icon', models.CharField(choices=[('twf-cleaning-1', 'twf-cleaning-1'), ('twf-cleaning-2', 'twf-cleaning-2'), ('twf-cleaning-3', 'twf-cleaning-3')], max_length=14)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
